/**
 * arcasha-orchestrator — Verifier (EXP-0005D)
 *
 * サブタスク結果の検証 (スコア閾値 + 拒否語) と統合 (ロール順レポート)。
 */

import type { EvalResult, Subtask } from 'arcasha-core';

export interface Verification {
  subtask: Subtask;
  nodeId: string;
  passed: boolean;
  score: number;
  reason: string;
}

export class Verifier {
  constructor(private readonly threshold = 0.4) {}

  verify(subtask: Subtask, result: EvalResult): Verification {
    const refusal = ['sorry', 'cannot', 'unable', 'as an ai', 'i am'];
    const hasRefusal = refusal.some(k => result.text.toLowerCase().includes(k));
    const passed = result.score >= this.threshold && !hasRefusal;
    const reason = hasRefusal
      ? `refusal detected (score=${result.score.toFixed(3)})`
      : `score=${result.score.toFixed(3)} ${passed ? '>= threshold' : '< threshold'} (${this.threshold})`;
    return { subtask, nodeId: result.nodeId, passed, score: result.score, reason };
  }

  integrate(subtasks: Subtask[], results: Record<string, EvalResult>): string {
    const parts: string[] = [];
    for (const st of [...subtasks].sort((a, b) => a.order - b.order)) {
      const r = results[st.id];
      if (r) {
        parts.push(`## ${st.role} (${st.capability})\n${r.text.trim()}`);
      }
    }
    const header = `# Integrated Result\n\nGenerated by ArcAsha arcasha-orchestrator (Belief-Driven AI Orchestration)\n`;
    return header + parts.join('\n\n');
  }
}
